// src/sw.ts
export type { };
declare const self: ServiceWorkerGlobalScope & { __WB_MANIFEST: Array<{ revision: string | null, url: string }> };

const CACHE_NAME = "sovereign-ai-core-v3";

// CRITICAL: This is the injection point for Vite PWA. 
// During the build, Workbox replaces this with the actual array of compiled files.
const manifest = self.__WB_MANIFEST || [];

self.addEventListener("install", (event: any) => {
  self.skipWaiting();
  
  // Pre-cache all the compiled assets generated by Vite for offline use
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      const urlsToCache = manifest.map((entry) => entry.url);
      return cache.addAll(urlsToCache);
    })
  );
});

self.addEventListener("activate", (event: any) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k))
      );
      await self.clients.claim();
    })()
  );
});

self.addEventListener("fetch", (event: any) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  // CRITICAL: Explicitly ignore .gguf files to prevent duplicating 400MB in the SW cache
  const isCoreAsset = [".wasm", ".js", ".css", ".html", ".json"].some(ext => url.pathname.endsWith(ext)) && !url.pathname.endsWith('.gguf');

  if (isCoreAsset) {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE_NAME);
        const cachedResponse = await cache.match(event.request);

        if (cachedResponse) {
          return cachedResponse;
        }

        try {
          const networkResponse = await fetch(event.request);
          if (networkResponse.status === 200) {
            await cache.put(event.request, networkResponse.clone());
          }
          return networkResponse;
        } catch (error) {
          return new Response("Offline execution failure: Asset not found in local cache.", {
            status: 503,
            statusText: "Service Unavailable"
          });
        }
      })()
    );
  }
});